### PR TITLE
fix: removes legacy createElement in favor h

### PR DESCRIPTION
**Pull request by miguelrk**
## Problem
The `@vue/composition-api` package is now stable and createElement was replaced with h. The current workaround throws **build errors on vite** (especially when building in cloud services).

## Open Issues
- #504 
- #574 

**Refers to @marshallswain's comment [here](https://github.com/feathersjs-ecosystem/feathers-vuex/issues/504#issuecomment-901308727):**

> @philipimperato I don't believe so. I can do a quick patch release if somebody wants to update the code to only work with the latest @vue/composition-api. I _think_ that's all that needs to happen at this point.

## Proposed Solution:
This PR simply updates the FeathersVuexPagination component to use `h` and removes the legacy `createElement` function. A new release should mark the v1 version of the composition-api as required.

Thanks to the Feathers team! :heart:

### CODE REVIEW

**Comment by marshallswain** [comment]
@miguelrk thanks for doing this.  Any idea why the tests are failing with this error?

```
12:33:24 PM: src/FeathersVuexPagination.ts(2,3): error TS2614: Module '"../node_modules/@vue/composition-api/dist"' has no exported member 'h'. Did you mean to use 'import h from "../node_modules/@vue/composition-api/dist"' instead?
```

You can review the build log here if that helps: https://app.netlify.com/sites/feathers-vuex/deploys/618d6fc4590936000737b670

**Comment by miguelrk** [comment]
Of course 👍🏼.

Hadn't seen the tests failed. I believe it might be due to the version of the composition-api. I tried it locally with `"@vue/composition-api": "^1.2.4"` and it indeed worked. `feathers-vuex` is currently using `"@vue/composition-api": "^0.6.1"`, by bad, I forgot to update the dependency here as well. Will do...

**Comment by miguelrk** [comment]
@marshallswain great! That was it

**Comment by marshallswain** [comment]
Awesome.  I'll shoot for a release later today.

**Comment by miguelrk** [comment]
Hey @marshallswain, sorry for the insistence, would you mind doing the quick release? 😁  I'd appreciate it, thanks again!

**Comment by marshallswain** [comment]
I'm finally getting to this, now.  :)

**Comment by marshallswain** [comment]
Which version of feathers-Vuex are you currently using? @miguelrk

**Comment by miguelrk** [comment]
I'm currently using "feathers-vuex"​: ​"​^3.16.0​"​. I'm already using dove but I'm still stuck with vue2. This PR makes it work for vite, which was really the only thing causing issue.

**Comment by marshallswain** [comment]
Ok. There’sa problem with the tests that I’ll need to figure out.

On November 16, 2021, GitHub ***@***.***> wrote:
> I'm currently using "feathers-vuex"​: ​"​^3.16.0​"​. I'm already using
> dove but I'm still stuck with vue2. This PR makes it work for vite,
> which was really the only thing causing issue.
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/feathersjs-ecosystem/feathers-
vuex/pull/612#issuecomment-969991265>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAA7OWJC7S4DUZO3VJ4RWCLUMIGUJANCNFSM5H3GFDUA>.

**Comment by miguelrk** [comment]
Sure thing, let me know if I can help out 👍🏼

**Comment by marshallswain** [comment]
@miguelrk The only error left is "no response from localhost:3030" which I believe is coming from the client/server integration tests.  It probably means that the package that handles HTTP request mocking is somehow broken.  I think I might move the tests to use feathers-memory instead of mocking feathers-rest.

**Comment by FossPrime** [comment]
@miguelrk why are you stuck on Vue 2 aside from feathers-vuex@4 not being stable? (I'm also waiting an update to feathers-vuex 3.16 with a patch for what this PR is addressing)

**Comment by miguelrk** [comment]
Oh @rayfoss it's not really feathers related. It's because of Vuetify which I use for the UI (waiting for vue3 support). Feathers is running smooth in v5 (dove) already for a couple of months now 👍🏼

**Comment by TheNoim** [comment]
The version with this fixed isn't published, am I correct?

**Pull request merged**
