### PR TITLE
"Update" paginationData if find has finished

### PR DESCRIPTION
**Pull request by anli-xsigns**
I use a watcher in my component watching for changes on paginationData:
```
const { items, isPending, paginationData } = useFind({
  model: Building,
  params: queryParams
});

watch(paginationData, paginationDataParam => {
  if (paginationDataParam && paginationDataParam.default && paginationDataParam.default.mostRecent)
    variables.pagination.rowsNumber = paginationDataParam.default.mostRecent.total;
  else
    variables.pagination.rowsNumber = 0;
});
```
This didn't work after find operation was successful made because the computed paginationData does not update on change of the pagination object in the vuex state.
```
paginationData: computed(() => {
  return model.store.state[model.servicePath].pagination;
}),
```
Therefore I suggest to make it dependant on state.isPending which is set if a find operation is made and successful:
```
paginationData: computed(() => {
  if (!state.isPending)
    return model.store.state[model.servicePath].pagination;
  else
    return {};
}),
```

### Summary

(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))

- [ ] Tell us about the problem your pull request is solving.
- [ ] Are there any open issues that are related to this?
- [ ] Is this PR dependent on PRs in other repos?

If so, please mention them to keep the conversations linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).

Thanks for contributing to Feathers! :heart:

### CODE REVIEW

**Comment by marshallswain** [comment]
> This didn't work after find operation was successful made because the computed paginationData does not update on change of the pagination object in the vuex state.

^^^ This is probably root of the issue.  I'll look into this a bit more.

**Comment by marshallswain** [comment]
@anli-xsigns will you check if version `3.8.1` fixes the issue for you?  Thanks!

**Comment by marshallswain** [comment]
I believe this should be resolved after the mentioned updates.  Feel free to reopen if more is needed.

**Comment by litti** [comment]
Sorry for being unresponsive the last days - I had a lot of work because operation in the vacation rental business ;-)
I tried 3.9.1 and it works well. Thanks a lot!

**Comment by marshallswain** [comment]
Awesome! Thanks for the update. Cheers

**Pull request closed without merging**
