### PR TITLE
fix:  make createElement compatible with 1.0.0 of @vue/composition-api

### PR DESCRIPTION
**Pull request by phatj**
### Summary

This PR allows the usage of @vue/composition-api v1.0.0 and below as a peer dependency by dynamically using either `createElement` or `h`, whichever exists.

- [x] Tell us about the problem your pull request is solving.
- [x] Are there any open issues that are related to this?
#504 
- [x] Is this PR dependent on PRs in other repos?
no

### Other Information

I am not sure if this requires a documentation update or integration testing.

### CODE REVIEW

**Comment by J3m5** [comment]
I'm afraid that doing `import * as Composition from '@vue/composition-api'` will prevent tree-shaking with webpack or others.

**Comment by phatj** [comment]
Hi @J3m5!

Good catch, I did not think about tree shaking, but I did get the idea for using a wildcard import by browsing the source of the @vue/composition-api package as it seems like wildcard exports are used [fairly](https://github.com/vuejs/composition-api/blob/master/src/index.ts) [liberally](https://github.com/vuejs/composition-api/blob/master/src/apis/index.ts).

I'm doing some more reading on tree shaking and it seems that since webpack 4, it uses a more robust analyzer for dead code elimination rather than a scan of import names.
* https://medium.com/@kz228747/tree-shaking-webpack-4-c33ce1e31e5c
* https://medium.com/@zwegrzyniak/webpack-4-1-and-es-modules-esm-dd0bd7dca4da

> An other solution would be to only support the last version of the plugin and update the version of the plugin in the package.json.

That's a great idea!  I was exploring this solution as I was inspired by Marshal's last comment in #504.

Also, there is another option:  the [createElement](https://github.com/vuejs/composition-api/blob/master/src/apis/createElement.ts) source shows that it is still exported as `createElement`, and is aliased later on [here](https://github.com/vuejs/composition-api/blob/master/src/apis/index.ts#L9).

I'm away from my machine right now, but if we just import this one function directly, feathers-vuex should be able to function normally without having to do any monkey business with wilcard exports 😄 

Let me know your thoughts! ❤️

**Comment by J3m5** [comment]
> I'm super hesitant to wildcard import the entire thing. We may just need to drop support for the old syntax and do a wholesale upgrade and major version bump.

I agree

**Comment by phatj** [comment]
Awesome, just updated the branch @marshallswain.  Let me know if there's anything else this PR needs.

**Comment by marshallswain** [comment]
Thank you!

**Pull request merged**
